# Generated by Django 3.1.7 on 2021-04-01 09:23

from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactpage',
            name='from_address',
            field=models.EmailField(default='stevestanleyweb@gmail.com', help_text='Email address to use to send email from.', max_length=254),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='thank_you_text',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='Message to user on submission of form.'),
        ),
    ]
