# Generated by Django 3.1.7 on 2021-02-25 19:48

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.embeds.blocks
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_auto_20210225_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalpage',
            name='body',
            field=wagtail.core.fields.StreamField([('paragraph', wagtail.core.blocks.StructBlock([('text', wagtail.core.blocks.RichTextBlock(help_text='Text to display'))])), ('text_and_image', wagtail.core.blocks.StructBlock([('text', wagtail.core.blocks.RichTextBlock(help_text='Text to display')), ('image', wagtail.images.blocks.ImageChooserBlock(help_text='Image will be resized to 570x370px'))])), ('embed', wagtail.embeds.blocks.EmbedBlock())], blank=True, null=True),
        ),
    ]
