# Generated by Django 3.1.7 on 2021-03-12 09:35

from django.db import migrations
import home.blocks
import wagtail.contrib.table_block.blocks
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.documents.blocks
import wagtail.embeds.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0006_auto_20210226_0810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalpage',
            name='body',
            field=wagtail.core.fields.StreamField([('column_block', wagtail.core.blocks.StructBlock([('content', wagtail.core.blocks.StreamBlock([('paragraph', wagtail.core.blocks.StructBlock([('text', wagtail.core.blocks.RichTextBlock(help_text='Text to display'))])), ('video', wagtail.core.blocks.StructBlock([('video', wagtail.embeds.blocks.EmbedBlock(help_text='Embed a video from Youtube')), ('caption', wagtail.core.blocks.CharBlock(help_text='Optional caption for video', max_length=50, required=False))])), ('download', wagtail.core.blocks.StructBlock([('button_title', wagtail.core.blocks.CharBlock(help_text='Text to go on download button', max_length=25, required=True)), ('downloadable_file', wagtail.documents.blocks.DocumentChooserBlock(help='Document to download', required=True))])), ('quote', wagtail.core.blocks.StructBlock([('text', wagtail.core.blocks.TextBlock(label='Quote Text', required=True, rows=4)), ('author', wagtail.core.blocks.CharBlock(label='Author', max_length=255, required=False))])), ('image_gallery', wagtail.core.blocks.StructBlock([('collection', home.blocks.CollectionChooserBlock(label='Image Collection', required=True))])), ('table', wagtail.core.blocks.StructBlock([('table', wagtail.contrib.table_block.blocks.TableBlock())])), ('map', wagtail.core.blocks.StructBlock([('search', wagtail.core.blocks.CharBlock(help_text='Address or search term used to find your location on the map.', label='Location', max_length=255, required=True))]))], label='Content'))])), ('paragraph', wagtail.core.blocks.StructBlock([('text', wagtail.core.blocks.RichTextBlock(help_text='Text to display'))])), ('video', wagtail.core.blocks.StructBlock([('video', wagtail.embeds.blocks.EmbedBlock(help_text='Embed a video from Youtube')), ('caption', wagtail.core.blocks.CharBlock(help_text='Optional caption for video', max_length=50, required=False))])), ('download', wagtail.core.blocks.StructBlock([('button_title', wagtail.core.blocks.CharBlock(help_text='Text to go on download button', max_length=25, required=True)), ('downloadable_file', wagtail.documents.blocks.DocumentChooserBlock(help='Document to download', required=True))])), ('quote', wagtail.core.blocks.StructBlock([('text', wagtail.core.blocks.TextBlock(label='Quote Text', required=True, rows=4)), ('author', wagtail.core.blocks.CharBlock(label='Author', max_length=255, required=False))])), ('image_gallery', wagtail.core.blocks.StructBlock([('collection', home.blocks.CollectionChooserBlock(label='Image Collection', required=True))])), ('table', wagtail.core.blocks.StructBlock([('table', wagtail.contrib.table_block.blocks.TableBlock())])), ('map', wagtail.core.blocks.StructBlock([('search', wagtail.core.blocks.CharBlock(help_text='Address or search term used to find your location on the map.', label='Location', max_length=255, required=True))]))], blank=True, null=True),
        ),
    ]
