# Generated by Django 3.1.7 on 2021-03-16 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0009_auto_20210316_0853'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalpage',
            name='comments',
            field=models.BooleanField(default=False),
        ),
    ]
