# Generated by Django 3.1.7 on 2021-03-19 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_seriespage_number_in_series'),
    ]

    operations = [
        migrations.AddField(
            model_name='seriespage',
            name='summary',
            field=models.CharField(default='summary', help_text='A short summary to go into links.', max_length=250),
            preserve_default=False,
        ),
    ]
