# Generated by Django 3.1.7 on 2021-03-01 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsitesettings',
            name='site_copyright',
            field=models.CharField(blank=True, help_text="The copyright owner to be displayed on the site footer. Don't enter the © symbol", max_length=50, null=True),
        ),
    ]
