# Generated by Django 3.1.7 on 2021-03-16 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0002_globalsitesettings_site_copyright'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsitesettings',
            name='disqus_site_name',
            field=models.CharField(blank=True, help_text='Write a valid disqus shortname here to enable comments on the site. https://disqus.com/', max_length=50, null=True),
        ),
    ]
