# Generated by Django 3.1.7 on 2021-04-01 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0060_fix_workflow_unique_constraint'),
        ('site_settings', '0004_socialmediasettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('footer_btn_link', models.URLField(blank=True, help_text="Optional link to that will prominantly display in the site's footer", null=True, verbose_name='Footer button link')),
                ('footer_btn_text', models.CharField(blank=True, default='Find out more', help_text='Text for the optional footer link.', max_length=50)),
                ('footer_btn_page', models.ForeignKey(blank=True, help_text='Select an internal site page', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
