# Generated by Django 3.1.7 on 2021-03-01 10:21

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import modelcluster.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0060_fix_workflow_unique_constraint'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The name you want to give to this menu.', max_length=100)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, help_text='The name used internally in html templates to include the menu.', populate_from='title')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('link_title', models.CharField(blank=True, help_text='What will appear on the page as a link', max_length=50)),
                ('link_url', models.CharField(blank=True, help_text='Link to an external page', max_length=500)),
                ('open_in_new_tab', models.BooleanField(blank=True, default=False, help_text='Should the page open in a new tab?')),
                ('link_page', models.ForeignKey(blank=True, help_text='Link to a page on this site.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailcore.page')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='menus.menu')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
