# Generated by Django 3.1.7 on 2021-03-01 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='link_title',
            field=models.CharField(blank=True, help_text='Optional. Default link title will be the page tile, you can overwrite this.', max_length=50),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='link_url',
            field=models.CharField(blank=True, help_text='Optinal. Link to an external page. Internal pages will always take priority if both are set.', max_length=500),
        ),
    ]
