# Generated by Django 3.1.7 on 2021-03-01 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0002_auto_20210301_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='link_url',
            field=models.CharField(blank=True, help_text='Optional. Link to an external page. Internal pages will always take priority if both are set.', max_length=500),
        ),
    ]
