# Generated by Django 3.1.7 on 2021-02-25 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(help_text='The name of the prouct type i.e. Computers', max_length=50, verbose_name='Product category')),
                ('descriptive_text', models.TextField(help_text="A short description to go on the product category's home page card", max_length=100, null=True)),
                ('product_category_image', models.ForeignKey(help_text='An image to represent the product category type', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, help_text='The product price in GBP', max_digits=5, null=True)),
                ('product_name', models.CharField(max_length=50, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='products.productcategory')),
                ('product_image', models.ForeignKey(help_text='An image to represent the product', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
        ),
    ]
