# Generated by Django 3.1.7 on 2021-02-26 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210226_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategorypage',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='products.productcategory'),
        ),
    ]
