# Generated by Django 3.1.7 on 2021-02-26 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20210226_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpage',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='products.product'),
        ),
    ]
